secret = "3"
token_id = "1"
owner_pub_key = "4"
merkle_proof = ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
leaf_index = "0"
root = "9980736400551739115772753311330232508374029367967213745682802767452879725004"
nullifier = "13341430947752852071942613006416654588749196012973063432873197485821390898187"
token_id_public = "1"
recipient = "5"
