leaf_index = "0"
merkle_proof = ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
new_commitment = "6729172553928561804196267770118455776407999104311641384478181339669600824650"
new_pub_key = "4"
new_secret = "3"
nullifier = "17343884395475564396822359909476696947510519694780554538443565409649983639559"
old_pub_key = "2"
old_root = "2227386657343832452321909471015998694755839766857535260915716217922017046171"
old_secret = "1"
token_id = "1"
