secret = "1"
token_id = "1"
owner_pub_key = "2"
metadata_hash_private = "11259375"
merkle_proof = ["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0"]
leaf_index = "0"
root = "2227386657343832452321909471015998694755839766857535260915716217922017046171"
nullifier = "17343884395475564396822359909476696947510519694780554538443565409649983639559"
metadata_hash = "11259375"
